---
root: true

plugins:
  - babel

env:
  node: true
  browser: true
  jest: true

parser: "@babel/eslint-parser"
parserOptions: {
  requireConfigFile: false,
}

extends:
  - "airbnb-base"

rules:
  no-console: 0
  import/extensions: 0
  import/no-extraneous-dependencies: ["error", {"devDependencies": ["**/*.test.js", "**/*.spec.js"]}]